# Evaluation demo
This notebook reproduces the evaluation framework of the Formula 1 Retrieval-Augmented Generation (RAG) chatbot.

In [1]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

from evaluation import (
    evaluate_retrieval_metrics,
    evaluate_generation_metrics,
    evaluate_latency,
    evaluate_sources_and_citations
)

Retrieval metrics

In [3]:
retrieval_results = evaluate_retrieval_metrics(top_k=5)

retrieval_df = pd.DataFrame(retrieval_results)

retrieval_df

2026-06-12 00:00:38,431 [INFO] Loading embedding model 'multi-qa-MiniLM-L6-cos-v1' …
2026-06-12 00:00:38,454 [INFO] No device provided, using mps
2026-06-12 00:00:38,626 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-12 00:00:38,627 [WARNING] Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-12 00:00:38,637 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/modules.json "HTTP/1.1 200 OK"
2026-06-12 00:00:38,765 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:38,777 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-06-12 00:00:38,784 [INFO] Loading SentenceTransformer model from sentence-transformers/multi-qa-MiniLM-L6-cos-v1.
2026-06-12 00:00:38,908 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:38,922 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-06-12 00:00:39,046 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:39,059 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/README.md "HTTP/1.1 200 OK"
2026-06-12 00:00:39,183 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:39,198 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/modules.json "HTTP/1.1 200 OK"
2026-06-12 00:00:39,361 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:39,376 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-06-12 00:00:39,504 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-06-12 00:00:39,632 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:39,643 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

2026-06-12 00:00:39,890 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-06-12 00:00:40,024 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-12 00:00:40,157 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-12 00:00:40,282 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-12 00:00:40,405 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:40,425 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-12 00:00:40,556 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:40,570 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/config.json "HTTP/1.1 200 OK"
2026-06-12 00:00:40,698 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:40,709 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/config.json "HTTP/1.1 200 OK"
2026-06-12 00:00:40,835 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:40,850 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-12 00:00:41,000 [INFO] HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-12 00:00:41,126 [INFO] HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-12 00:00:41,296 [INFO] HTTP Request: HEAD https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-12 00:00:41,305 [INFO] HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/b207367332321f8e44f96e224ef15bc607f4dbf0/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-06-12 00:00:41,437 [INFO] HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/multi-qa-MiniLM-L6-cos-v1 "HTTP/1.1 200 OK"
2026-06-12 00:00:41,902 [INFO] Loading FAISS index from disk …
2026-06-12 00:00:41,931 [INFO]   Loaded 4300 vectors.
2026-06-12 00:00:41,931 [INFO] FAISS index already populated (4300 vectors). Skipping ingestion.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,question,expected_sources,retrieved_sources,precision@5,recall@5,mrr
0,How many Formula One World Drivers' Championsh...,[max_verstappen_chunks.json],"[max_verstappen_chunks.json, max_verstappen_ch...",0.8,1.0,1.0
1,What is the Circuit de Monaco and what major r...,[circuit_de_monaco_chunks.json],"[circuit_de_monaco_chunks.json, circuit_de_mon...",1.0,1.0,1.0
2,What type of engines are currently used in For...,[formula_one_engines_chunks.json],"[formula_one_engines_chunks.json, formula_one_...",1.0,1.0,1.0
3,When was the modern Formula One World Champion...,[history_of_formula_one_chunks.json],"[history_of_formula_one_chunks.json, fédératio...",0.6,1.0,1.0
4,What are the primary goals of Formula One regu...,[formula_one_regulations_chunks.json],"[formula_one_regulations_chunks.json, formula_...",1.0,1.0,1.0

In [4]:
print(
    f"Average Precision@5: "
    f"{retrieval_df['precision@5'].mean():.3f}"
)

print(
    f"Average Recall@5: "
    f"{retrieval_df['recall@5'].mean():.3f}"
)

print(
    f"Average MRR: "
    f"{retrieval_df['mrr'].mean():.3f}"
)

Average Precision@5: 0.880
Average Recall@5: 1.000
Average MRR: 1.000

Generation metrics

In [5]:
generation_results = evaluate_generation_metrics(top_k=5)

generation_df = pd.DataFrame(generation_results)

generation_df

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:00:48,140 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:00:58,621 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:03,312 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:08,120 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:12,096 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,question,ground_truth_answer,generated_answer,sources,faithfulness_score_1_to_5,relevance_score_1_to_5,correctness_score_1_to_5
0,How many Formula One World Drivers' Championsh...,Max Verstappen has won four Formula One World ...,"According to [1], Max Verstappen has won four ...","[{'title': 'Max Verstappen', 'section': '', 'u...",4,5,5
1,What is the Circuit de Monaco and what major r...,The Circuit de Monaco is a 3.337 km street cir...,The Circuit de Monaco is a circuit used by var...,"[{'title': 'Circuit de Monaco', 'section': 'FI...",4,4,4
2,What type of engines are currently used in For...,Formula One currently uses 1.6-litre four-stro...,"According to [2], the current engines used in ...","[{'title': 'Formula One engines', 'section': '...",5,4,4
3,When was the modern Formula One World Champion...,The foundation of modern Formula One began wit...,According to [4] History of Formula One › Era ...,"[{'title': 'History of Formula One', 'section'...",4,4,4
4,What are the primary goals of Formula One regu...,The primary goals of Formula One regulations a...,"According to [1], the primary goals of the For...","[{'title': 'Formula One regulations', 'section...",5,4,5

Latency evaluation

In [6]:
latency_results = evaluate_latency(top_k=5)

latency_df = pd.DataFrame(latency_results)

latency_df

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:14,265 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:19,516 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:22,173 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:24,251 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:26,219 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

,question,retrieval_latency_seconds,generation_latency_seconds
0,How many Formula One World Drivers' Championsh...,0.025884,1.971600
1,What is the Circuit de Monaco and what major r...,0.057271,5.196154
2,What type of engines are currently used in For...,0.206903,2.445711
3,When was the modern Formula One World Champion...,0.059630,2.019393
4,What are the primary goals of Formula One regu...,0.059857,1.906866

In [7]:
print(
    f"Average Retrieval Latency: "
    f"{latency_df['retrieval_latency_seconds'].mean():.3f} seconds"
)

print(
    f"Average Generation Latency: "
    f"{latency_df['generation_latency_seconds'].mean():.3f} seconds"
)

Average Retrieval Latency: 0.082 seconds
Average Generation Latency: 2.708 seconds

Sources evaluation

In [8]:
citation_results = evaluate_sources_and_citations(top_k=5)

citation_df = pd.DataFrame(citation_results)

citation_df

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:28,169 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:35,699 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:38,899 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:40,975 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-12 00:01:43,438 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"

,question,expected_sources,returned_sources,has_sources,contains_expected_source
0,How many Formula One World Drivers' Championsh...,[max_verstappen_chunks.json],"[{'title': 'Max Verstappen', 'section': '', 'u...",True,True
1,What is the Circuit de Monaco and what major r...,[circuit_de_monaco_chunks.json],"[{'title': 'Circuit de Monaco', 'section': 'FI...",True,True
2,What type of engines are currently used in For...,[formula_one_engines_chunks.json],"[{'title': 'Formula One engines', 'section': '...",True,True
3,When was the modern Formula One World Champion...,[history_of_formula_one_chunks.json],"[{'title': 'History of Formula One', 'section'...",True,True
4,What are the primary goals of Formula One regu...,[formula_one_regulations_chunks.json],"[{'title': 'Formula One regulations', 'section...",True,True

In [9]:
print(
    f"Percentage of answers containing citations: "
    f"{citation_df['has_sources'].mean()*100:.1f}%"
)

print(
    f"Percentage of answers containing expected citations: "
    f"{citation_df['contains_expected_source'].mean()*100:.1f}%"
)

Percentage of answers containing citations: 100.0%
Percentage of answers containing expected citations: 100.0%